import type { Technique } from "../../src/lib/types.ts";

/** Starter technique cards for a white belt. Only inserted when the library is empty. */
export const STARTER: Array<Pick<Technique, "name" | "position" | "type" | "steps" | "details" | "mistakes">> = [
  { name: "Escape de cadera (camarón)", position: "Escapes", type: "escape", steps: "1. Marcos en cadera y hombro\n2. Puente para hacer espacio\n3. Girá de costado, empujá con el pie y llevá la cadera atrás", details: "Mové la cadera, no la cabeza. Marcos firmes y codos pegados.", mistakes: "Empujar con los brazos en vez de la cadera. Quedarse de espalda plana." },
  { name: "Upa (puente y giro)", position: "Mount", type: "escape", steps: "1. Atrapá un brazo y el pie del mismo lado\n2. Puente alto sobre el hombro atrapado\n3. Girá y caé en su guardia", details: "Puente en diagonal sobre el hombro, no hacia arriba. Atrapá el brazo por encima del codo.", mistakes: "Hacer el puente derecho hacia arriba. Dejarle apoyar la mano libre." },
  { name: "Escape codo-rodilla desde montada", position: "Mount", type: "escape", steps: "1. Marco en la cadera\n2. Camarón y meté la rodilla\n3. Recuperá media guardia y después guardia completa", details: "Combinalo con la upa: cuando apoye la mano, cambiá a codo-rodilla.", mistakes: "Marcos flojos que le dejan subir a montada alta." },
  { name: "Escape de cien kilos a guardia", position: "Side Control", type: "escape", steps: "1. Marcos en cuello y cadera\n2. Puente hacia el rival\n3. Camarón, meté la rodilla y recuperá la guardia", details: "Primero el puente para sacarte el peso, después el camarón. Codo cercano adentro.", mistakes: "Hacer camarón sin puente. Abrazarle la espalda." },
  { name: "Raspado tijera", position: "Closed Guard", type: "sweep", steps: "1. Agarre de solapa y manga\n2. Canilla cruzada en la panza, la otra pierna abajo\n3. Traelo hacia adelante y cerrá la tijera", details: "Desequilibralo hacia adelante antes de la tijera. Primero sacá la cadera al costado.", mistakes: "Intentar el raspado de espalda plana." },
  { name: "Raspado de cadera", position: "Closed Guard", type: "sweep", steps: "1. Sentate apoyado en una mano\n2. Empujá la cadera hacia su axila\n3. Girá y caé montado", details: "Encadenalo con kimura y guillotina cuando apoye la mano.", mistakes: "No sentarse lo suficiente. Empuje de cadera lento." },
  { name: "Estrangulación cruzada", position: "Closed Guard", type: "submission", steps: "1. Primer agarre profundo, palma arriba\n2. Segundo agarre por arriba o por abajo\n3. Codos abajo y traelo hacia vos", details: "El primer agarre tiene que ser profundo, detrás del cuello. Rompé la postura antes.", mistakes: "Agarres cortos y codos abiertos." },
  { name: "Palanca de brazo desde guardia cerrada", position: "Closed Guard", type: "submission", steps: "1. Controlá el brazo cruzando la línea media\n2. Sacá la cadera y pasá la pierna por la cara\n3. Apretá las rodillas y levantá la cadera", details: "El ángulo es todo: ponete perpendicular antes de pasar la pierna.", mistakes: "Quedarse de frente. Dejar espacio entre las rodillas." },
  { name: "Pasaje knee cut", position: "Guard Passing", type: "pass", steps: "1. Agarrá solapa y pantalón\n2. Deslizá la rodilla cruzando el muslo\n3. Underhook y hombro a la cara", details: "Mantené el pie lejano clavado. Cabeza del lado lejano.", mistakes: "Postura muy alta que le deja sacar el underhook." },
  { name: "Retención de guardia básica", position: "Open Guard", type: "concept", steps: "Marcos, cadera, pies en cadera o bíceps, siempre de frente al que pasa", details: "Si te pasa las rodillas, camarón y volvé a meter la pierna. No le des la espalda.", mistakes: "Girarse y entregar la espalda." },
  { name: "Mata león", position: "Back", type: "submission", steps: "1. Cinturón de seguridad y ganchos\n2. Brazo que estrangula bajo el mentón\n3. Mano al bíceps, la otra detrás de la cabeza", details: "Escondé la mano que estrangula y entrá bajo el mentón con el codo alineado.", mistakes: "Cruzar los pies. Buscar la estrangulación antes del control." },
  { name: "Derribo a dos piernas", position: "Standing / Takedowns", type: "takedown", steps: "1. Bajá el nivel\n2. Paso de penetración, cabeza afuera\n3. Empujá y girá la esquina", details: "Cabeza arriba, espalda recta, empujá con las piernas.", mistakes: "Doblarse en la cintura con la cabeza abajo." },
];
