import type { Technique } from "../../src/lib/types.ts";

/** Starter technique cards for a white belt. Only inserted when the library is empty. */
export const STARTER: Array<Pick<Technique, "name" | "position" | "type" | "steps" | "details" | "mistakes">> = [
  { name: "Hip escape (shrimp)", position: "Escapes", type: "escape", steps: "1. Frame on hip and shoulder\n2. Bridge to make space\n3. Turn on side, push off the foot, hips back", details: "Move your hips, not your head. Frames stay connected, elbows tight.", mistakes: "Pushing with arms instead of hips. Staying flat." },
  { name: "Bridge and roll (upa)", position: "Mount", type: "escape", steps: "1. Trap one arm and the same-side foot\n2. Bridge high over the trapped shoulder\n3. Roll into their guard", details: "Bridge diagonally over the shoulder, not straight up. Trap the arm above the elbow.", mistakes: "Bridging straight up. Letting them post the free hand." },
  { name: "Elbow-knee escape from mount", position: "Mount", type: "escape", steps: "1. Frame on hip\n2. Shrimp and slide knee under\n3. Recover half guard then full guard", details: "Combine with the upa: when they post, switch to elbow-knee.", mistakes: "Frames too loose, letting them go high mount." },
  { name: "Side control escape to guard", position: "Side Control", type: "escape", steps: "1. Frame on neck and hip\n2. Bridge into them\n3. Shrimp away, knee in, recover guard", details: "Bridge first to unload their weight, then shrimp. Keep the near elbow in.", mistakes: "Shrimping without bridging. Reaching around their back." },
  { name: "Scissor sweep", position: "Closed Guard", type: "sweep", steps: "1. Grip collar and sleeve\n2. Shin across the belly, other leg low\n3. Pull them forward, scissor the legs", details: "Get them off balance forward before you scissor. Hips out to the side first.", mistakes: "Trying to sweep from flat on the back." },
  { name: "Hip bump sweep", position: "Closed Guard", type: "sweep", steps: "1. Sit up on one hand\n2. Post, hip into their armpit\n3. Roll over into mount", details: "Chain with kimura and guillotine when they post.", mistakes: "Not sitting up high enough. Slow hip drive." },
  { name: "Cross collar choke", position: "Closed Guard", type: "submission", steps: "1. Deep first grip, palm up\n2. Second grip over or under\n3. Elbows down, pull them in", details: "The first grip must be deep, behind the neck. Break posture first.", mistakes: "Shallow grips, flaring elbows." },
  { name: "Armbar from closed guard", position: "Closed Guard", type: "submission", steps: "1. Control arm across the centre line\n2. Hip out, leg over the face\n3. Squeeze knees, lift hips", details: "Angle is everything: get perpendicular before the leg goes over.", mistakes: "Staying square. Leaving space between knees." },
  { name: "Knee cut pass", position: "Guard Passing", type: "pass", steps: "1. Grip collar and pants\n2. Knee slides across the thigh\n3. Underhook, drive shoulder to face", details: "Keep the far foot pinned. Head on the far side.", mistakes: "Posture too high, letting them underhook." },
  { name: "Guard retention basics", position: "Open Guard", type: "concept", steps: "Frames, hips, feet on hips or biceps, always face the passer", details: "When they get past your knees, hip escape and re-insert. Do not turn away.", mistakes: "Turning away and giving the back." },
  { name: "Rear naked choke", position: "Back", type: "submission", steps: "1. Seatbelt, hooks in\n2. Choking arm under the chin\n3. Hand to the bicep, other hand behind the head", details: "Hide the choking hand, go under the chin with the elbow in line with the chin.", mistakes: "Crossing feet. Fighting for the choke before control." },
  { name: "Double leg takedown", position: "Standing / Takedowns", type: "takedown", steps: "1. Level change\n2. Penetration step, head outside\n3. Drive and turn the corner", details: "Head up, back straight, drive through with the legs.", mistakes: "Bending at the waist, head down." },
];
